### ISSUE TITLE
New GO terms not 'fully' loaded in Noctua? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#72]
Hello, 

In the Pathway Editor, a new GO term, GO:0141125, is findable by ID or by label, but when added to an activity unit, the label does not show up, and the box containing that term cannot be connected (see screenshot). 

<img width="796" alt="GO-CAM" src="https://github.com/geneontology/noctua-visual-pathway-editor/assets/4782928/1efbbf45-0765-432f-9570-d8b64ac716e6">

Reported by @sylvainpoux

I dont know if this is a Form or a NEO (or another) issue.

@kltm @balhoff @tmushayahama 

Thanks, Pascale

**Comment by pgaudet** [comment]
@kltm do you know the cause of this issue? Is the autocomplete a different version from what's in NEO?

**Comment by kltm** [comment]
@pgaudet The ground truth for what's loaded in the autocomplete is: http://noctua-amigo.berkeleybop.org/amigo/search/ontology ; the ground truth for what minerva thinks is going on is `http://wok.lbl.gov:6800` with the secret path of `status`. For specifically VPE issues, if not one of the above, @tmushayahama would probably have a clearer understanding.

**Comment by kltm** [comment]
@pgaudet For noctua (minerva), it is loading the materialized http://skyhook.berkeleybop.org/go-lego-reacto.owl (do not try and view in browser). This is produced in the `issue-35-neo-test` pipeline (~once a week). So what's in there? That appears to be https://github.com/geneontology/pipeline/blob/issue-35-neo-test/Jenkinsfile#L370-L376, which would mean that essentially minerva loads whatever the last success "NEO" pipeline run was, using the current ontology states at that point, delta imports. @balhoff may no more off the top of his head if there are locked import statements in there to `release` or `snapshot`; if not, I can recursively dig down more.

**Comment by kltm** [comment]
@pgaudet Which model is this again?
Talking to @balhoff and looking at the Makefile, the data should be updated to the last NEO build at every restart.

**Comment by kltm** [comment]
@balhoff Also thinks this may be fixed; could you recheck?

**Comment by pgaudet** [comment]
Yes, this is fixed for the term I gave you. I was just wondering what caused this; is this to be expected for any new term?

**Comment by kltm** [comment]
@pgaudet I think we talked about this on the last software call, first item(?). IIRC, the conclusion was that it would be just lag (or upstream issue) and should essentially always be the latest when rebuilt (unless we missed an import wrinkle).

**Comment by tmushayahama** [comment]
Is there any change on the ui side? Also to add, if a term is not resolved on minerva (no label), it will not have a root type, i.e if it 
 is an MF, BP or CC. therefore we do not allow connection if it is not an MF. 

tagging @kltm @pgaudet

**Comment by pgaudet** [comment]
I guess we can close this, it was just really weird that the term was not fully imported. It seems like we cannot identify the source of the problem
